### ISSUE TITLE
check genbank input for CDS

### ISSUE THREAD

**Issue by Perugolate** [wdingx/pan-genome-analysis#1]
Maybe throw an error/warning at step03 if a gbk input contains no CDS entries.
Currently, the pipeline creates empty faa for gbk with no annotations, and then runs until step06 before throwing:

```
======  starting step06: align genes in geneCluster by mafft and build gene trees
Traceback (most recent call last):
  File "/pan-genome-analysis/panX.py", line 287, in <module>
    myPangenome.process_clusters()
  File "/pan-genome-analysis/scripts/pangenome_computation.py", line 180, in process_clusters
    myClusterCollector.estimate_raw_core_diversity()
  File "/pan-genome-analysis/scripts/cluster_collective_processing.py", line 17, in estimate_raw_core_diversity
    self.folders_dict, self.strain_list, self.threads, self.core_genome_threshold, self.factor_core_diversity, self.species)
  File "/pan-genome-analysis/scripts/sf_core_diversity.py", line 102, in estimate_core_gene_diversity
    calculated_core_diversity=tmp_average_core_diversity(tmp_core_seq_path)
  File "/pan-genome-analysis/scripts/sf_core_diversity.py", line 42, in tmp_average_core_diversity
    with open(file_path+'tmp_core_diversity.txt', 'r') as tmp_core_diversity_file:
IOError: [Errno 2] No such file or directory: '/panx/sanger/protein_faa/diamond_matches/tmp_core/tmp_core_diversity.txt'
```

**Comment by wdingx** [comment]
Thanks for reporting this. A gbk file without any CDS seems a bit odd (at least, this hasn't happened before for RefSeq data). Could you send me your example file? I will add a warning regarding this issue.

**Comment by Perugolate** [comment]
Yeah it's annoying. When downloading all 251 *Streptococcus equi* genomes from ncbi, 8 of the gbk files contain no CDS. e.g. :

[GCA_001509635.1_ASM150963v1_genomic.gbk.txt](https://github.com/wdingx/pan-genome-analysis/files/1689617/GCA_001509635.1_ASM150963v1_genomic.gbk.txt)

**Comment by wdingx** [comment]
Many thanks for providing the file. It contains only one contig and no annotation.
Now, the checking of CDS is added. If there are genomes having no CDS, panX will give a warning and list those genomes.
Please let me know whether this helps you.

**Comment by Perugolate** [comment]
Cheers
